// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	reflect "reflect"

	mock "github.com/stretchr/testify/mock"
)

// Arg is an autogenerated mock type for the Arg type
type Arg struct {
	mock.Mock
}

type Arg_Expecter struct {
	mock *mock.Mock
}

func (_m *Arg) EXPECT() *Arg_Expecter {
	return &Arg_Expecter{mock: &_m.Mock}
}

// String provides a mock function with given fields:
func (_m *Arg) String() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Arg_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type Arg_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *Arg_Expecter) String() *Arg_String_Call {
	return &Arg_String_Call{Call: _e.mock.On("String")}
}

func (_c *Arg_String_Call) Run(run func()) *Arg_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Arg_String_Call) Return(_a0 string) *Arg_String_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Arg_String_Call) RunAndReturn(run func() string) *Arg_String_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function with given fields:
func (_m *Arg) Type() reflect.Type {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 reflect.Type
	if rf, ok := ret.Get(0).(func() reflect.Type); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(reflect.Type)
		}
	}

	return r0
}

// Arg_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type Arg_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *Arg_Expecter) Type() *Arg_Type_Call {
	return &Arg_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *Arg_Type_Call) Run(run func()) *Arg_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Arg_Type_Call) Return(_a0 reflect.Type) *Arg_Type_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Arg_Type_Call) RunAndReturn(run func() reflect.Type) *Arg_Type_Call {
	_c.Call.Return(run)
	return _c
}

// NewArg creates a new instance of Arg. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewArg(t interface {
	mock.TestingT
	Cleanup(func())
}) *Arg {
	mock := &Arg{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
