// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"reflect"

	"github.com/michalkurzeja/godi/v2/di"
	mock "github.com/stretchr/testify/mock"
)

// NewCompilerOp creates a new instance of CompilerOp. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCompilerOp(t interface {
	mock.TestingT
	Cleanup(func())
}) *CompilerOp {
	mock := &CompilerOp{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CompilerOp is an autogenerated mock type for the CompilerOp type
type CompilerOp struct {
	mock.Mock
}

type CompilerOp_Expecter struct {
	mock *mock.Mock
}

func (_m *CompilerOp) EXPECT() *CompilerOp_Expecter {
	return &CompilerOp_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type CompilerOp
func (_mock *CompilerOp) Run(builder *di.ContainerBuilder) error {
	ret := _mock.Called(builder)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*di.ContainerBuilder) error); ok {
		r0 = returnFunc(builder)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CompilerOp_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type CompilerOp_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - builder *di.ContainerBuilder
func (_e *CompilerOp_Expecter) Run(builder any) *CompilerOp_Run_Call {
	return &CompilerOp_Run_Call{Call: _e.mock.On("Run", builder)}
}

func (_c *CompilerOp_Run_Call) Run(run func(builder *di.ContainerBuilder)) *CompilerOp_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *di.ContainerBuilder
		if args[0] != nil {
			arg0 = args[0].(*di.ContainerBuilder)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CompilerOp_Run_Call) Return(err error) *CompilerOp_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CompilerOp_Run_Call) RunAndReturn(run func(builder *di.ContainerBuilder) error) *CompilerOp_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewDefinition creates a new instance of Definition. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDefinition(t interface {
	mock.TestingT
	Cleanup(func())
}) *Definition {
	mock := &Definition{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Definition is an autogenerated mock type for the Definition type
type Definition struct {
	mock.Mock
}

type Definition_Expecter struct {
	mock *mock.Mock
}

func (_m *Definition) EXPECT() *Definition_Expecter {
	return &Definition_Expecter{mock: &_m.Mock}
}

// ID provides a mock function for the type Definition
func (_mock *Definition) ID() di.ID {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 di.ID
	if returnFunc, ok := ret.Get(0).(func() di.ID); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(di.ID)
	}
	return r0
}

// Definition_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type Definition_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *Definition_Expecter) ID() *Definition_ID_Call {
	return &Definition_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *Definition_ID_Call) Run(run func()) *Definition_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Definition_ID_Call) Return(iD di.ID) *Definition_ID_Call {
	_c.Call.Return(iD)
	return _c
}

func (_c *Definition_ID_Call) RunAndReturn(run func() di.ID) *Definition_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Labels provides a mock function for the type Definition
func (_mock *Definition) Labels() []di.Label {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Labels")
	}

	var r0 []di.Label
	if returnFunc, ok := ret.Get(0).(func() []di.Label); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]di.Label)
		}
	}
	return r0
}

// Definition_Labels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Labels'
type Definition_Labels_Call struct {
	*mock.Call
}

// Labels is a helper method to define mock.On call
func (_e *Definition_Expecter) Labels() *Definition_Labels_Call {
	return &Definition_Labels_Call{Call: _e.mock.On("Labels")}
}

func (_c *Definition_Labels_Call) Run(run func()) *Definition_Labels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Definition_Labels_Call) Return(labels []di.Label) *Definition_Labels_Call {
	_c.Call.Return(labels)
	return _c
}

func (_c *Definition_Labels_Call) RunAndReturn(run func() []di.Label) *Definition_Labels_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function for the type Definition
func (_mock *Definition) Type() reflect.Type {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 reflect.Type
	if returnFunc, ok := ret.Get(0).(func() reflect.Type); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(reflect.Type)
		}
	}
	return r0
}

// Definition_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type Definition_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *Definition_Expecter) Type() *Definition_Type_Call {
	return &Definition_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *Definition_Type_Call) Run(run func()) *Definition_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Definition_Type_Call) Return(typeParam reflect.Type) *Definition_Type_Call {
	_c.Call.Return(typeParam)
	return _c
}

func (_c *Definition_Type_Call) RunAndReturn(run func() reflect.Type) *Definition_Type_Call {
	_c.Call.Return(run)
	return _c
}
