log-level: "warn"
all: true
dir: "{{.InterfaceDir}}/mocks"
outpkg: "mocks"
filename: "{{.InterfaceName | snakecase}}.go"
mockname: "{{.InterfaceName}}"
recursive: true
packages:
  github.com/michalkurzeja/godi/v2:

# Deprecations compliance
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true