// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	di "github.com/michalkurzeja/godi/v2/di"
	mock "github.com/stretchr/testify/mock"
)

// BuilderOption is an autogenerated mock type for the BuilderOption type
type BuilderOption struct {
	mock.Mock
}

type BuilderOption_Expecter struct {
	mock *mock.Mock
}

func (_m *BuilderOption) EXPECT() *BuilderOption_Expecter {
	return &BuilderOption_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *BuilderOption) Execute(_a0 *di.Config) {
	_m.Called(_a0)
}

// BuilderOption_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type BuilderOption_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *di.Config
func (_e *BuilderOption_Expecter) Execute(_a0 interface{}) *BuilderOption_Execute_Call {
	return &BuilderOption_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *BuilderOption_Execute_Call) Run(run func(_a0 *di.Config)) *BuilderOption_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*di.Config))
	})
	return _c
}

func (_c *BuilderOption_Execute_Call) Return() *BuilderOption_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *BuilderOption_Execute_Call) RunAndReturn(run func(*di.Config)) *BuilderOption_Execute_Call {
	_c.Run(run)
	return _c
}

// NewBuilderOption creates a new instance of BuilderOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBuilderOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *BuilderOption {
	mock := &BuilderOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
