// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"io"
	"reflect"

	"github.com/michalkurzeja/godi/v2"
	"github.com/michalkurzeja/godi/v2/graph"
	mock "github.com/stretchr/testify/mock"
)

// NewContainer creates a new instance of Container. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewContainer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Container {
	mock := &Container{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Container is an autogenerated mock type for the Container type
type Container struct {
	mock.Mock
}

type Container_Expecter struct {
	mock *mock.Mock
}

func (_m *Container) EXPECT() *Container_Expecter {
	return &Container_Expecter{mock: &_m.Mock}
}

// ExecuteFunction provides a mock function for the type Container
func (_mock *Container) ExecuteFunction(id di.ID) ([]any, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteFunction")
	}

	var r0 []any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(di.ID) ([]any, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(di.ID) []any); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(di.ID) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Container_ExecuteFunction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteFunction'
type Container_ExecuteFunction_Call struct {
	*mock.Call
}

// ExecuteFunction is a helper method to define mock.On call
//   - id di.ID
func (_e *Container_Expecter) ExecuteFunction(id any) *Container_ExecuteFunction_Call {
	return &Container_ExecuteFunction_Call{Call: _e.mock.On("ExecuteFunction", id)}
}

func (_c *Container_ExecuteFunction_Call) Run(run func(id di.ID)) *Container_ExecuteFunction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 di.ID
		if args[0] != nil {
			arg0 = args[0].(di.ID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Container_ExecuteFunction_Call) Return(vs []any, err error) *Container_ExecuteFunction_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *Container_ExecuteFunction_Call) RunAndReturn(run func(id di.ID) ([]any, error)) *Container_ExecuteFunction_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteFunctions provides a mock function for the type Container
func (_mock *Container) ExecuteFunctions(ids ...di.ID) ([][]any, error) {
	var tmpRet mock.Arguments
	if len(ids) > 0 {
		tmpRet = _mock.Called(ids)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ExecuteFunctions")
	}

	var r0 [][]any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(...di.ID) ([][]any, error)); ok {
		return returnFunc(ids...)
	}
	if returnFunc, ok := ret.Get(0).(func(...di.ID) [][]any); ok {
		r0 = returnFunc(ids...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(...di.ID) error); ok {
		r1 = returnFunc(ids...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Container_ExecuteFunctions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteFunctions'
type Container_ExecuteFunctions_Call struct {
	*mock.Call
}

// ExecuteFunctions is a helper method to define mock.On call
//   - ids ...di.ID
func (_e *Container_Expecter) ExecuteFunctions(ids ...any) *Container_ExecuteFunctions_Call {
	return &Container_ExecuteFunctions_Call{Call: _e.mock.On("ExecuteFunctions",
		append([]any{}, ids...)...)}
}

func (_c *Container_ExecuteFunctions_Call) Run(run func(ids ...di.ID)) *Container_ExecuteFunctions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []di.ID
		var variadicArgs []di.ID
		if len(args) > 0 {
			variadicArgs = args[0].([]di.ID)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *Container_ExecuteFunctions_Call) Return(results [][]any, err error) *Container_ExecuteFunctions_Call {
	_c.Call.Return(results, err)
	return _c
}

func (_c *Container_ExecuteFunctions_Call) RunAndReturn(run func(ids ...di.ID) ([][]any, error)) *Container_ExecuteFunctions_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteFunctionsByLabel provides a mock function for the type Container
func (_mock *Container) ExecuteFunctionsByLabel(label di.Label) ([][]any, error) {
	ret := _mock.Called(label)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteFunctionsByLabel")
	}

	var r0 [][]any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(di.Label) ([][]any, error)); ok {
		return returnFunc(label)
	}
	if returnFunc, ok := ret.Get(0).(func(di.Label) [][]any); ok {
		r0 = returnFunc(label)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(di.Label) error); ok {
		r1 = returnFunc(label)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Container_ExecuteFunctionsByLabel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteFunctionsByLabel'
type Container_ExecuteFunctionsByLabel_Call struct {
	*mock.Call
}

// ExecuteFunctionsByLabel is a helper method to define mock.On call
//   - label di.Label
func (_e *Container_Expecter) ExecuteFunctionsByLabel(label any) *Container_ExecuteFunctionsByLabel_Call {
	return &Container_ExecuteFunctionsByLabel_Call{Call: _e.mock.On("ExecuteFunctionsByLabel", label)}
}

func (_c *Container_ExecuteFunctionsByLabel_Call) Run(run func(label di.Label)) *Container_ExecuteFunctionsByLabel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 di.Label
		if args[0] != nil {
			arg0 = args[0].(di.Label)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Container_ExecuteFunctionsByLabel_Call) Return(vss [][]any, err error) *Container_ExecuteFunctionsByLabel_Call {
	_c.Call.Return(vss, err)
	return _c
}

func (_c *Container_ExecuteFunctionsByLabel_Call) RunAndReturn(run func(label di.Label) ([][]any, error)) *Container_ExecuteFunctionsByLabel_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteFunctionsByType provides a mock function for the type Container
func (_mock *Container) ExecuteFunctionsByType(typ reflect.Type) ([][]any, error) {
	ret := _mock.Called(typ)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteFunctionsByType")
	}

	var r0 [][]any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(reflect.Type) ([][]any, error)); ok {
		return returnFunc(typ)
	}
	if returnFunc, ok := ret.Get(0).(func(reflect.Type) [][]any); ok {
		r0 = returnFunc(typ)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(reflect.Type) error); ok {
		r1 = returnFunc(typ)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Container_ExecuteFunctionsByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteFunctionsByType'
type Container_ExecuteFunctionsByType_Call struct {
	*mock.Call
}

// ExecuteFunctionsByType is a helper method to define mock.On call
//   - typ reflect.Type
func (_e *Container_Expecter) ExecuteFunctionsByType(typ any) *Container_ExecuteFunctionsByType_Call {
	return &Container_ExecuteFunctionsByType_Call{Call: _e.mock.On("ExecuteFunctionsByType", typ)}
}

func (_c *Container_ExecuteFunctionsByType_Call) Run(run func(typ reflect.Type)) *Container_ExecuteFunctionsByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 reflect.Type
		if args[0] != nil {
			arg0 = args[0].(reflect.Type)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Container_ExecuteFunctionsByType_Call) Return(vss [][]any, err error) *Container_ExecuteFunctionsByType_Call {
	_c.Call.Return(vss, err)
	return _c
}

func (_c *Container_ExecuteFunctionsByType_Call) RunAndReturn(run func(typ reflect.Type) ([][]any, error)) *Container_ExecuteFunctionsByType_Call {
	_c.Call.Return(run)
	return _c
}

// GetFunctionsIDsByLabel provides a mock function for the type Container
func (_mock *Container) GetFunctionsIDsByLabel(label di.Label) []di.ID {
	ret := _mock.Called(label)

	if len(ret) == 0 {
		panic("no return value specified for GetFunctionsIDsByLabel")
	}

	var r0 []di.ID
	if returnFunc, ok := ret.Get(0).(func(di.Label) []di.ID); ok {
		r0 = returnFunc(label)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]di.ID)
		}
	}
	return r0
}

// Container_GetFunctionsIDsByLabel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFunctionsIDsByLabel'
type Container_GetFunctionsIDsByLabel_Call struct {
	*mock.Call
}

// GetFunctionsIDsByLabel is a helper method to define mock.On call
//   - label di.Label
func (_e *Container_Expecter) GetFunctionsIDsByLabel(label any) *Container_GetFunctionsIDsByLabel_Call {
	return &Container_GetFunctionsIDsByLabel_Call{Call: _e.mock.On("GetFunctionsIDsByLabel", label)}
}

func (_c *Container_GetFunctionsIDsByLabel_Call) Run(run func(label di.Label)) *Container_GetFunctionsIDsByLabel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 di.Label
		if args[0] != nil {
			arg0 = args[0].(di.Label)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Container_GetFunctionsIDsByLabel_Call) Return(vs []di.ID) *Container_GetFunctionsIDsByLabel_Call {
	_c.Call.Return(vs)
	return _c
}

func (_c *Container_GetFunctionsIDsByLabel_Call) RunAndReturn(run func(label di.Label) []di.ID) *Container_GetFunctionsIDsByLabel_Call {
	_c.Call.Return(run)
	return _c
}

// GetFunctionsIDsByType provides a mock function for the type Container
func (_mock *Container) GetFunctionsIDsByType(typ reflect.Type) []di.ID {
	ret := _mock.Called(typ)

	if len(ret) == 0 {
		panic("no return value specified for GetFunctionsIDsByType")
	}

	var r0 []di.ID
	if returnFunc, ok := ret.Get(0).(func(reflect.Type) []di.ID); ok {
		r0 = returnFunc(typ)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]di.ID)
		}
	}
	return r0
}

// Container_GetFunctionsIDsByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFunctionsIDsByType'
type Container_GetFunctionsIDsByType_Call struct {
	*mock.Call
}

// GetFunctionsIDsByType is a helper method to define mock.On call
//   - typ reflect.Type
func (_e *Container_Expecter) GetFunctionsIDsByType(typ any) *Container_GetFunctionsIDsByType_Call {
	return &Container_GetFunctionsIDsByType_Call{Call: _e.mock.On("GetFunctionsIDsByType", typ)}
}

func (_c *Container_GetFunctionsIDsByType_Call) Run(run func(typ reflect.Type)) *Container_GetFunctionsIDsByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 reflect.Type
		if args[0] != nil {
			arg0 = args[0].(reflect.Type)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Container_GetFunctionsIDsByType_Call) Return(vs []di.ID) *Container_GetFunctionsIDsByType_Call {
	_c.Call.Return(vs)
	return _c
}

func (_c *Container_GetFunctionsIDsByType_Call) RunAndReturn(run func(typ reflect.Type) []di.ID) *Container_GetFunctionsIDsByType_Call {
	_c.Call.Return(run)
	return _c
}

// GetService provides a mock function for the type Container
func (_mock *Container) GetService(id di.ID) (any, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetService")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(di.ID) (any, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(di.ID) any); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(di.ID) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Container_GetService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetService'
type Container_GetService_Call struct {
	*mock.Call
}

// GetService is a helper method to define mock.On call
//   - id di.ID
func (_e *Container_Expecter) GetService(id any) *Container_GetService_Call {
	return &Container_GetService_Call{Call: _e.mock.On("GetService", id)}
}

func (_c *Container_GetService_Call) Run(run func(id di.ID)) *Container_GetService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 di.ID
		if args[0] != nil {
			arg0 = args[0].(di.ID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Container_GetService_Call) Return(v any, err error) *Container_GetService_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *Container_GetService_Call) RunAndReturn(run func(id di.ID) (any, error)) *Container_GetService_Call {
	_c.Call.Return(run)
	return _c
}

// GetServices provides a mock function for the type Container
func (_mock *Container) GetServices(ids ...di.ID) ([]any, error) {
	var tmpRet mock.Arguments
	if len(ids) > 0 {
		tmpRet = _mock.Called(ids)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetServices")
	}

	var r0 []any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(...di.ID) ([]any, error)); ok {
		return returnFunc(ids...)
	}
	if returnFunc, ok := ret.Get(0).(func(...di.ID) []any); ok {
		r0 = returnFunc(ids...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(...di.ID) error); ok {
		r1 = returnFunc(ids...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Container_GetServices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServices'
type Container_GetServices_Call struct {
	*mock.Call
}

// GetServices is a helper method to define mock.On call
//   - ids ...di.ID
func (_e *Container_Expecter) GetServices(ids ...any) *Container_GetServices_Call {
	return &Container_GetServices_Call{Call: _e.mock.On("GetServices",
		append([]any{}, ids...)...)}
}

func (_c *Container_GetServices_Call) Run(run func(ids ...di.ID)) *Container_GetServices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []di.ID
		var variadicArgs []di.ID
		if len(args) > 0 {
			variadicArgs = args[0].([]di.ID)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *Container_GetServices_Call) Return(svcs []any, err error) *Container_GetServices_Call {
	_c.Call.Return(svcs, err)
	return _c
}

func (_c *Container_GetServices_Call) RunAndReturn(run func(ids ...di.ID) ([]any, error)) *Container_GetServices_Call {
	_c.Call.Return(run)
	return _c
}

// GetServicesByLabel provides a mock function for the type Container
func (_mock *Container) GetServicesByLabel(label di.Label) ([]any, error) {
	ret := _mock.Called(label)

	if len(ret) == 0 {
		panic("no return value specified for GetServicesByLabel")
	}

	var r0 []any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(di.Label) ([]any, error)); ok {
		return returnFunc(label)
	}
	if returnFunc, ok := ret.Get(0).(func(di.Label) []any); ok {
		r0 = returnFunc(label)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(di.Label) error); ok {
		r1 = returnFunc(label)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Container_GetServicesByLabel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServicesByLabel'
type Container_GetServicesByLabel_Call struct {
	*mock.Call
}

// GetServicesByLabel is a helper method to define mock.On call
//   - label di.Label
func (_e *Container_Expecter) GetServicesByLabel(label any) *Container_GetServicesByLabel_Call {
	return &Container_GetServicesByLabel_Call{Call: _e.mock.On("GetServicesByLabel", label)}
}

func (_c *Container_GetServicesByLabel_Call) Run(run func(label di.Label)) *Container_GetServicesByLabel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 di.Label
		if args[0] != nil {
			arg0 = args[0].(di.Label)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Container_GetServicesByLabel_Call) Return(vs []any, err error) *Container_GetServicesByLabel_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *Container_GetServicesByLabel_Call) RunAndReturn(run func(label di.Label) ([]any, error)) *Container_GetServicesByLabel_Call {
	_c.Call.Return(run)
	return _c
}

// GetServicesByType provides a mock function for the type Container
func (_mock *Container) GetServicesByType(typ reflect.Type) ([]any, error) {
	ret := _mock.Called(typ)

	if len(ret) == 0 {
		panic("no return value specified for GetServicesByType")
	}

	var r0 []any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(reflect.Type) ([]any, error)); ok {
		return returnFunc(typ)
	}
	if returnFunc, ok := ret.Get(0).(func(reflect.Type) []any); ok {
		r0 = returnFunc(typ)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(reflect.Type) error); ok {
		r1 = returnFunc(typ)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Container_GetServicesByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServicesByType'
type Container_GetServicesByType_Call struct {
	*mock.Call
}

// GetServicesByType is a helper method to define mock.On call
//   - typ reflect.Type
func (_e *Container_Expecter) GetServicesByType(typ any) *Container_GetServicesByType_Call {
	return &Container_GetServicesByType_Call{Call: _e.mock.On("GetServicesByType", typ)}
}

func (_c *Container_GetServicesByType_Call) Run(run func(typ reflect.Type)) *Container_GetServicesByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 reflect.Type
		if args[0] != nil {
			arg0 = args[0].(reflect.Type)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Container_GetServicesByType_Call) Return(vs []any, err error) *Container_GetServicesByType_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *Container_GetServicesByType_Call) RunAndReturn(run func(typ reflect.Type) ([]any, error)) *Container_GetServicesByType_Call {
	_c.Call.Return(run)
	return _c
}

// GetServicesIDsByLabel provides a mock function for the type Container
func (_mock *Container) GetServicesIDsByLabel(label di.Label) []di.ID {
	ret := _mock.Called(label)

	if len(ret) == 0 {
		panic("no return value specified for GetServicesIDsByLabel")
	}

	var r0 []di.ID
	if returnFunc, ok := ret.Get(0).(func(di.Label) []di.ID); ok {
		r0 = returnFunc(label)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]di.ID)
		}
	}
	return r0
}

// Container_GetServicesIDsByLabel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServicesIDsByLabel'
type Container_GetServicesIDsByLabel_Call struct {
	*mock.Call
}

// GetServicesIDsByLabel is a helper method to define mock.On call
//   - label di.Label
func (_e *Container_Expecter) GetServicesIDsByLabel(label any) *Container_GetServicesIDsByLabel_Call {
	return &Container_GetServicesIDsByLabel_Call{Call: _e.mock.On("GetServicesIDsByLabel", label)}
}

func (_c *Container_GetServicesIDsByLabel_Call) Run(run func(label di.Label)) *Container_GetServicesIDsByLabel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 di.Label
		if args[0] != nil {
			arg0 = args[0].(di.Label)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Container_GetServicesIDsByLabel_Call) Return(vs []di.ID) *Container_GetServicesIDsByLabel_Call {
	_c.Call.Return(vs)
	return _c
}

func (_c *Container_GetServicesIDsByLabel_Call) RunAndReturn(run func(label di.Label) []di.ID) *Container_GetServicesIDsByLabel_Call {
	_c.Call.Return(run)
	return _c
}

// GetServicesIDsByType provides a mock function for the type Container
func (_mock *Container) GetServicesIDsByType(typ reflect.Type) []di.ID {
	ret := _mock.Called(typ)

	if len(ret) == 0 {
		panic("no return value specified for GetServicesIDsByType")
	}

	var r0 []di.ID
	if returnFunc, ok := ret.Get(0).(func(reflect.Type) []di.ID); ok {
		r0 = returnFunc(typ)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]di.ID)
		}
	}
	return r0
}

// Container_GetServicesIDsByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServicesIDsByType'
type Container_GetServicesIDsByType_Call struct {
	*mock.Call
}

// GetServicesIDsByType is a helper method to define mock.On call
//   - typ reflect.Type
func (_e *Container_Expecter) GetServicesIDsByType(typ any) *Container_GetServicesIDsByType_Call {
	return &Container_GetServicesIDsByType_Call{Call: _e.mock.On("GetServicesIDsByType", typ)}
}

func (_c *Container_GetServicesIDsByType_Call) Run(run func(typ reflect.Type)) *Container_GetServicesIDsByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 reflect.Type
		if args[0] != nil {
			arg0 = args[0].(reflect.Type)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Container_GetServicesIDsByType_Call) Return(vs []di.ID) *Container_GetServicesIDsByType_Call {
	_c.Call.Return(vs)
	return _c
}

func (_c *Container_GetServicesIDsByType_Call) RunAndReturn(run func(typ reflect.Type) []di.ID) *Container_GetServicesIDsByType_Call {
	_c.Call.Return(run)
	return _c
}

// Graph provides a mock function for the type Container
func (_mock *Container) Graph(cfg graph.Config) *graph.Graph {
	ret := _mock.Called(cfg)

	if len(ret) == 0 {
		panic("no return value specified for Graph")
	}

	var r0 *graph.Graph
	if returnFunc, ok := ret.Get(0).(func(graph.Config) *graph.Graph); ok {
		r0 = returnFunc(cfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*graph.Graph)
		}
	}
	return r0
}

// Container_Graph_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Graph'
type Container_Graph_Call struct {
	*mock.Call
}

// Graph is a helper method to define mock.On call
//   - cfg graph.Config
func (_e *Container_Expecter) Graph(cfg any) *Container_Graph_Call {
	return &Container_Graph_Call{Call: _e.mock.On("Graph", cfg)}
}

func (_c *Container_Graph_Call) Run(run func(cfg graph.Config)) *Container_Graph_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 graph.Config
		if args[0] != nil {
			arg0 = args[0].(graph.Config)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Container_Graph_Call) Return(graph1 *graph.Graph) *Container_Graph_Call {
	_c.Call.Return(graph1)
	return _c
}

func (_c *Container_Graph_Call) RunAndReturn(run func(cfg graph.Config) *graph.Graph) *Container_Graph_Call {
	_c.Call.Return(run)
	return _c
}

// HasFunction provides a mock function for the type Container
func (_mock *Container) HasFunction(id di.ID) bool {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for HasFunction")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(di.ID) bool); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Container_HasFunction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasFunction'
type Container_HasFunction_Call struct {
	*mock.Call
}

// HasFunction is a helper method to define mock.On call
//   - id di.ID
func (_e *Container_Expecter) HasFunction(id any) *Container_HasFunction_Call {
	return &Container_HasFunction_Call{Call: _e.mock.On("HasFunction", id)}
}

func (_c *Container_HasFunction_Call) Run(run func(id di.ID)) *Container_HasFunction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 di.ID
		if args[0] != nil {
			arg0 = args[0].(di.ID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Container_HasFunction_Call) Return(b bool) *Container_HasFunction_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Container_HasFunction_Call) RunAndReturn(run func(id di.ID) bool) *Container_HasFunction_Call {
	_c.Call.Return(run)
	return _c
}

// HasService provides a mock function for the type Container
func (_mock *Container) HasService(id di.ID) bool {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for HasService")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(di.ID) bool); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Container_HasService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasService'
type Container_HasService_Call struct {
	*mock.Call
}

// HasService is a helper method to define mock.On call
//   - id di.ID
func (_e *Container_Expecter) HasService(id any) *Container_HasService_Call {
	return &Container_HasService_Call{Call: _e.mock.On("HasService", id)}
}

func (_c *Container_HasService_Call) Run(run func(id di.ID)) *Container_HasService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 di.ID
		if args[0] != nil {
			arg0 = args[0].(di.ID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Container_HasService_Call) Return(b bool) *Container_HasService_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Container_HasService_Call) RunAndReturn(run func(id di.ID) bool) *Container_HasService_Call {
	_c.Call.Return(run)
	return _c
}

// Print provides a mock function for the type Container
func (_mock *Container) Print(w io.Writer) {
	_mock.Called(w)
	return
}

// Container_Print_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Print'
type Container_Print_Call struct {
	*mock.Call
}

// Print is a helper method to define mock.On call
//   - w io.Writer
func (_e *Container_Expecter) Print(w any) *Container_Print_Call {
	return &Container_Print_Call{Call: _e.mock.On("Print", w)}
}

func (_c *Container_Print_Call) Run(run func(w io.Writer)) *Container_Print_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 io.Writer
		if args[0] != nil {
			arg0 = args[0].(io.Writer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Container_Print_Call) Return() *Container_Print_Call {
	_c.Call.Return()
	return _c
}

func (_c *Container_Print_Call) RunAndReturn(run func(w io.Writer)) *Container_Print_Call {
	_c.Run(run)
	return _c
}
