// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	io "io"

	graph "github.com/michalkurzeja/godi/v2/graph"
	mock "github.com/stretchr/testify/mock"
)

// Encoder is an autogenerated mock type for the Encoder type
type Encoder struct {
	mock.Mock
}

type Encoder_Expecter struct {
	mock *mock.Mock
}

func (_m *Encoder) EXPECT() *Encoder_Expecter {
	return &Encoder_Expecter{mock: &_m.Mock}
}

// Encode provides a mock function with given fields: g, w
func (_m *Encoder) Encode(g *graph.Graph, w io.Writer) error {
	ret := _m.Called(g, w)

	if len(ret) == 0 {
		panic("no return value specified for Encode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*graph.Graph, io.Writer) error); ok {
		r0 = rf(g, w)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Encoder_Encode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encode'
type Encoder_Encode_Call struct {
	*mock.Call
}

// Encode is a helper method to define mock.On call
//   - g *graph.Graph
//   - w io.Writer
func (_e *Encoder_Expecter) Encode(g interface{}, w interface{}) *Encoder_Encode_Call {
	return &Encoder_Encode_Call{Call: _e.mock.On("Encode", g, w)}
}

func (_c *Encoder_Encode_Call) Run(run func(g *graph.Graph, w io.Writer)) *Encoder_Encode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*graph.Graph), args[1].(io.Writer))
	})
	return _c
}

func (_c *Encoder_Encode_Call) Return(_a0 error) *Encoder_Encode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Encoder_Encode_Call) RunAndReturn(run func(*graph.Graph, io.Writer) error) *Encoder_Encode_Call {
	_c.Call.Return(run)
	return _c
}

// Format provides a mock function with no fields
func (_m *Encoder) Format() graph.Format {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Format")
	}

	var r0 graph.Format
	if rf, ok := ret.Get(0).(func() graph.Format); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(graph.Format)
	}

	return r0
}

// Encoder_Format_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Format'
type Encoder_Format_Call struct {
	*mock.Call
}

// Format is a helper method to define mock.On call
func (_e *Encoder_Expecter) Format() *Encoder_Format_Call {
	return &Encoder_Format_Call{Call: _e.mock.On("Format")}
}

func (_c *Encoder_Format_Call) Run(run func()) *Encoder_Format_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Encoder_Format_Call) Return(_a0 graph.Format) *Encoder_Format_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Encoder_Format_Call) RunAndReturn(run func() graph.Format) *Encoder_Format_Call {
	_c.Call.Return(run)
	return _c
}

// NewEncoder creates a new instance of Encoder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEncoder(t interface {
	mock.TestingT
	Cleanup(func())
}) *Encoder {
	mock := &Encoder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
