// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"io"

	"github.com/michalkurzeja/godi/v2/graph"
	mock "github.com/stretchr/testify/mock"
)

// NewEncoder creates a new instance of Encoder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEncoder(t interface {
	mock.TestingT
	Cleanup(func())
}) *Encoder {
	mock := &Encoder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Encoder is an autogenerated mock type for the Encoder type
type Encoder struct {
	mock.Mock
}

type Encoder_Expecter struct {
	mock *mock.Mock
}

func (_m *Encoder) EXPECT() *Encoder_Expecter {
	return &Encoder_Expecter{mock: &_m.Mock}
}

// Encode provides a mock function for the type Encoder
func (_mock *Encoder) Encode(g *graph.Graph, w io.Writer) error {
	ret := _mock.Called(g, w)

	if len(ret) == 0 {
		panic("no return value specified for Encode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*graph.Graph, io.Writer) error); ok {
		r0 = returnFunc(g, w)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Encoder_Encode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encode'
type Encoder_Encode_Call struct {
	*mock.Call
}

// Encode is a helper method to define mock.On call
//   - g *graph.Graph
//   - w io.Writer
func (_e *Encoder_Expecter) Encode(g any, w any) *Encoder_Encode_Call {
	return &Encoder_Encode_Call{Call: _e.mock.On("Encode", g, w)}
}

func (_c *Encoder_Encode_Call) Run(run func(g *graph.Graph, w io.Writer)) *Encoder_Encode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *graph.Graph
		if args[0] != nil {
			arg0 = args[0].(*graph.Graph)
		}
		var arg1 io.Writer
		if args[1] != nil {
			arg1 = args[1].(io.Writer)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Encoder_Encode_Call) Return(err error) *Encoder_Encode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Encoder_Encode_Call) RunAndReturn(run func(g *graph.Graph, w io.Writer) error) *Encoder_Encode_Call {
	_c.Call.Return(run)
	return _c
}

// Format provides a mock function for the type Encoder
func (_mock *Encoder) Format() graph.Format {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Format")
	}

	var r0 graph.Format
	if returnFunc, ok := ret.Get(0).(func() graph.Format); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(graph.Format)
	}
	return r0
}

// Encoder_Format_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Format'
type Encoder_Format_Call struct {
	*mock.Call
}

// Format is a helper method to define mock.On call
func (_e *Encoder_Expecter) Format() *Encoder_Format_Call {
	return &Encoder_Format_Call{Call: _e.mock.On("Format")}
}

func (_c *Encoder_Format_Call) Run(run func()) *Encoder_Format_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Encoder_Format_Call) Return(format graph.Format) *Encoder_Format_Call {
	_c.Call.Return(format)
	return _c
}

func (_c *Encoder_Format_Call) RunAndReturn(run func() graph.Format) *Encoder_Format_Call {
	_c.Call.Return(run)
	return _c
}

// NewValidator creates a new instance of Validator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Validator {
	mock := &Validator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Validator is an autogenerated mock type for the Validator type
type Validator struct {
	mock.Mock
}

type Validator_Expecter struct {
	mock *mock.Mock
}

func (_m *Validator) EXPECT() *Validator_Expecter {
	return &Validator_Expecter{mock: &_m.Mock}
}

// Check provides a mock function for the type Validator
func (_mock *Validator) Check(g *graph.Graph) error {
	ret := _mock.Called(g)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*graph.Graph) error); ok {
		r0 = returnFunc(g)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Validator_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type Validator_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - g *graph.Graph
func (_e *Validator_Expecter) Check(g any) *Validator_Check_Call {
	return &Validator_Check_Call{Call: _e.mock.On("Check", g)}
}

func (_c *Validator_Check_Call) Run(run func(g *graph.Graph)) *Validator_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *graph.Graph
		if args[0] != nil {
			arg0 = args[0].(*graph.Graph)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Validator_Check_Call) Return(err error) *Validator_Check_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Validator_Check_Call) RunAndReturn(run func(g *graph.Graph) error) *Validator_Check_Call {
	_c.Call.Return(run)
	return _c
}

// NewSource creates a new instance of Source. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *Source {
	mock := &Source{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Source is an autogenerated mock type for the Source type
type Source struct {
	mock.Mock
}

type Source_Expecter struct {
	mock *mock.Mock
}

func (_m *Source) EXPECT() *Source_Expecter {
	return &Source_Expecter{mock: &_m.Mock}
}

// Graph provides a mock function for the type Source
func (_mock *Source) Graph(cfg graph.Config) (*graph.Graph, error) {
	ret := _mock.Called(cfg)

	if len(ret) == 0 {
		panic("no return value specified for Graph")
	}

	var r0 *graph.Graph
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(graph.Config) (*graph.Graph, error)); ok {
		return returnFunc(cfg)
	}
	if returnFunc, ok := ret.Get(0).(func(graph.Config) *graph.Graph); ok {
		r0 = returnFunc(cfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*graph.Graph)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(graph.Config) error); ok {
		r1 = returnFunc(cfg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Source_Graph_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Graph'
type Source_Graph_Call struct {
	*mock.Call
}

// Graph is a helper method to define mock.On call
//   - cfg graph.Config
func (_e *Source_Expecter) Graph(cfg any) *Source_Graph_Call {
	return &Source_Graph_Call{Call: _e.mock.On("Graph", cfg)}
}

func (_c *Source_Graph_Call) Run(run func(cfg graph.Config)) *Source_Graph_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 graph.Config
		if args[0] != nil {
			arg0 = args[0].(graph.Config)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Source_Graph_Call) Return(graph1 *graph.Graph, err error) *Source_Graph_Call {
	_c.Call.Return(graph1, err)
	return _c
}

func (_c *Source_Graph_Call) RunAndReturn(run func(cfg graph.Config) (*graph.Graph, error)) *Source_Graph_Call {
	_c.Call.Return(run)
	return _c
}
