// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	graph "github.com/michalkurzeja/godi/v2/graph"
	mock "github.com/stretchr/testify/mock"
)

// Source is an autogenerated mock type for the Source type
type Source struct {
	mock.Mock
}

type Source_Expecter struct {
	mock *mock.Mock
}

func (_m *Source) EXPECT() *Source_Expecter {
	return &Source_Expecter{mock: &_m.Mock}
}

// Graph provides a mock function with given fields: cfg
func (_m *Source) Graph(cfg graph.Config) *graph.Graph {
	ret := _m.Called(cfg)

	if len(ret) == 0 {
		panic("no return value specified for Graph")
	}

	var r0 *graph.Graph
	if rf, ok := ret.Get(0).(func(graph.Config) *graph.Graph); ok {
		r0 = rf(cfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*graph.Graph)
		}
	}

	return r0
}

// Source_Graph_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Graph'
type Source_Graph_Call struct {
	*mock.Call
}

// Graph is a helper method to define mock.On call
//   - cfg graph.Config
func (_e *Source_Expecter) Graph(cfg interface{}) *Source_Graph_Call {
	return &Source_Graph_Call{Call: _e.mock.On("Graph", cfg)}
}

func (_c *Source_Graph_Call) Run(run func(cfg graph.Config)) *Source_Graph_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(graph.Config))
	})
	return _c
}

func (_c *Source_Graph_Call) Return(_a0 *graph.Graph) *Source_Graph_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Source_Graph_Call) RunAndReturn(run func(graph.Config) *graph.Graph) *Source_Graph_Call {
	_c.Call.Return(run)
	return _c
}

// NewSource creates a new instance of Source. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *Source {
	mock := &Source{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
