// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	graph "github.com/michalkurzeja/godi/v2/graph"
	mock "github.com/stretchr/testify/mock"
)

// Validator is an autogenerated mock type for the Validator type
type Validator struct {
	mock.Mock
}

type Validator_Expecter struct {
	mock *mock.Mock
}

func (_m *Validator) EXPECT() *Validator_Expecter {
	return &Validator_Expecter{mock: &_m.Mock}
}

// Check provides a mock function with given fields: g
func (_m *Validator) Check(g *graph.Graph) error {
	ret := _m.Called(g)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*graph.Graph) error); ok {
		r0 = rf(g)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Validator_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type Validator_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - g *graph.Graph
func (_e *Validator_Expecter) Check(g interface{}) *Validator_Check_Call {
	return &Validator_Check_Call{Call: _e.mock.On("Check", g)}
}

func (_c *Validator_Check_Call) Run(run func(g *graph.Graph)) *Validator_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*graph.Graph))
	})
	return _c
}

func (_c *Validator_Check_Call) Return(_a0 error) *Validator_Check_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Validator_Check_Call) RunAndReturn(run func(*graph.Graph) error) *Validator_Check_Call {
	_c.Call.Return(run)
	return _c
}

// NewValidator creates a new instance of Validator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Validator {
	mock := &Validator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
